/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Logic.Parameters;
import java.awt.CardLayout;

/**
 *
 * @author Stacy
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startSelectMode1 = new View.StartSelectMode();
        standartOptionSettings1 = new View.StandartOptionSettings();
        advanceOptionSettings1 = new View.AdvanceOptionSettings();
        startGenerating1 = new View.StartGenerating();
        result1 = new View.Result();
        fileSystem1 = new View.FileSystem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generator GMW");
        setMaximumSize(new java.awt.Dimension(590, 480));
        setMinimumSize(new java.awt.Dimension(590, 480));
        setPreferredSize(new java.awt.Dimension(590, 480));
        setResizable(false);

        jPanel1.setLayout(new java.awt.CardLayout());
        jPanel1.add(startSelectMode1, "card2");
        jPanel1.add(standartOptionSettings1, "card3");
        jPanel1.add(advanceOptionSettings1, "card4");
        jPanel1.add(startGenerating1, "card5");
        jPanel1.add(result1, "card6");
        jPanel1.add(fileSystem1, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
                 Parameters parameters = new Parameters();
            }
        });
    }

    public void setOnTopStandartOption() {

        CardLayout layout = (CardLayout) jPanel1.getLayout();

        layout.show(jPanel1, "card3");

    }

    public void setOnTopAdvancetOption() {

        CardLayout layout = (CardLayout) jPanel1.getLayout();

        layout.show(jPanel1, "card4");

    }

    public void setOnTopStartSelectMode() {

        CardLayout layout = (CardLayout) jPanel1.getLayout();

        layout.show(jPanel1, "card2");

    }

    public void setOnTopStartGeneration() {

        CardLayout layout = (CardLayout) jPanel1.getLayout();

        layout.show(jPanel1, "card5");

    }

    public void setOnTopResult() {

        CardLayout layout = (CardLayout) jPanel1.getLayout();

        layout.show(jPanel1, "card6");

    }

    public void setOnTopFileSystem() {

        CardLayout layout = (CardLayout) jPanel1.getLayout();

        layout.show(jPanel1, "card7");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public View.AdvanceOptionSettings advanceOptionSettings1;
    private View.FileSystem fileSystem1;
    private javax.swing.JPanel jPanel1;
    public View.Result result1;
    public View.StandartOptionSettings standartOptionSettings1;
    public View.StartGenerating startGenerating1;
    private View.StartSelectMode startSelectMode1;
    // End of variables declaration//GEN-END:variables
}
